version: '3'
# First of all, need to create network with name 'sk'
#networks:
#  default:
#    external:
#      name: sk
services:
  sk-rabbitmq:
    image: rabbitmq:3.7.8-management
    container_name: "sk-rabbitmq"
    ports:
      - "15672:15672" # Management port
      - "5672:5672" # Service port
  sk-mongo:
    image: 'mongo:xenial'
    container_name: "sk-mongo"
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
      - MONGO_INITDB_DATABASE=sk-auth
    volumes:
      - ./data/db:/data/db
      - ./db/database-init.js:/docker-entrypoint-initdb.d/database-init.js
    ports:
      - 27017:27017
