version: '3'
services:
  mongodb:
    image: 'mongo:xenial'
    container_name: "mongodb"
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    volumes:
      - ./data/db:/data/db
      - ./db/database-init.js:/docker-entrypoint-initdb.d/database-init.js
    ports:
      - 27017:27017
    command: mongod --smallfiles --logpath=/dev/null