package api

// Message codes
const (
	_MAP_PAYLOAD_TO_USER_CODE    = 1
	_MAP_PAYLOAD_TO_SHORT_USER   = 2
	_MAP_PAYLOAD_TO_COMPLEX_USER = 3
	_MAP_PAYLOAD_TO_LOGIN_INFO   = 4
	_SUCCESSFULL_REGISTRATION    = 100
	_INVALID_REGISTRATION        = 101
	_INVALID_LOG_IN              = 102
	_SUCCESSFULL_LOG_IN          = 103
)
