package api

// Message codes
const (
	_MAP_PAYLOAD_TO_USER_CODE    = 1
	_MAP_PAYLOAD_TO_SHORT_USER   = 2
	_MAP_PAYLOAD_TO_COMPLEX_USER = 3
	_SUCCESSFULL_REGISTRATION    = 100
	_INVALID_REGISTRATION        = 101
)
